FROM alpine:3.23
RUN apk add --no-cache ca-certificates curl bind-tools netcat-openbsd nmap socat bash openssl tcpdump tcptraceroute strace iperf busybox-extras
WORKDIR /app
COPY ./bin/testapp /app/testapp
ENTRYPOINT ["/app/testapp"]
